// Base de datos de estudiantes colombianos
window.estudiantes = [
    {
        codigo: '2022101',
        tipoId: 'TI',
        numeroId: '1088456789',
        nombre: 'María Camila Rodríguez Gómez',
        grado: '10',
        grupo: 'A',
        estado: 'En curso',
        primerNombre: 'María',
        segundoNombre: 'Camila',
        primerApellido: 'Rodríguez',
        segundoApellido: 'Gómez',
        genero: 'F',
        fechaNacimiento: '2008-03-15',
        telefonoFijo: '6044567890',
        celular: '3001234567',
        gmail: 'mariacrodriguez08@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Carrera 45 #23-12 Apto 301',
        cursos: [
            { codigo: '2022101', año: '2022', grado: '10', grupo: 'A', estado: 'En curso', promedio: '' },
            { codigo: '2021102', año: '2021', grado: '9', grupo: 'B', estado: 'Aprobado', promedio: '4.2' },
            { codigo: '2020103', año: '2020', grado: '8', grupo: 'A', estado: 'Aprobado', promedio: '3.8' }
        ]
    },
    {
        codigo: '2022102',
        tipoId: 'TI',
        numeroId: '1089234567',
        nombre: 'Juan Sebastián Martínez López',
        grado: '10',
        grupo: 'A',
        estado: 'Aprobado',
        primerNombre: 'Juan',
        segundoNombre: 'Sebastián',
        primerApellido: 'Martínez',
        segundoApellido: 'López',
        genero: 'M',
        fechaNacimiento: '2008-07-22',
        telefonoFijo: '6045678901',
        celular: '3109876543',
        gmail: 'juansmartinez22@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Calle 50 #67-89',
        cursos: [
            { codigo: '2022102', año: '2022', grado: '10', grupo: 'A', estado: 'Aprobado', promedio: '4.5' },
            { codigo: '2021103', año: '2021', grado: '9', grupo: 'A', estado: 'Aprobado', promedio: '4.3' }
        ]
    },
    {
        codigo: '2022103',
        tipoId: 'CC',
        numeroId: '1090345678',
        nombre: 'Laura Daniela Hernández Pérez',
        grado: '10',
        grupo: 'B',
        estado: 'Reprobado',
        primerNombre: 'Laura',
        segundoNombre: 'Daniela',
        primerApellido: 'Hernández',
        segundoApellido: 'Pérez',
        genero: 'F',
        fechaNacimiento: '2007-11-08',
        telefonoFijo: '',
        celular: '3201234567',
        gmail: 'lauradhernandez07@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Avenida 80 #45-23',
        cursos: [
            { codigo: '2022103', año: '2022', grado: '10', grupo: 'B', estado: 'Reprobado', promedio: '2.4' },
            { codigo: '2021104', año: '2021', grado: '9', grupo: 'C', estado: 'Aprobado', promedio: '3.2' }
        ]
    },
    {
        codigo: '2022104',
        tipoId: 'TI',
        numeroId: '1088567890',
        nombre: 'Carlos Andrés Ramírez Torres',
        grado: '10',
        grupo: 'B',
        estado: 'En curso',
        primerNombre: 'Carlos',
        segundoNombre: 'Andrés',
        primerApellido: 'Ramírez',
        segundoApellido: 'Torres',
        genero: 'M',
        fechaNacimiento: '2008-05-19',
        telefonoFijo: '6046789012',
        celular: '3157654321',
        gmail: 'carlosramirez19@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Carrera 70 #12-34 Apto 501',
        cursos: [
            { codigo: '2022104', año: '2022', grado: '10', grupo: 'B', estado: 'En curso', promedio: '' }
        ]
    },
    {
        codigo: '2022105',
        tipoId: 'TI',
        numeroId: '1087678901',
        nombre: 'Ana María Moreno García',
        grado: '10',
        grupo: 'A',
        estado: 'En curso',
        primerNombre: 'Ana',
        segundoNombre: 'María',
        primerApellido: 'Moreno',
        segundoApellido: 'García',
        genero: 'F',
        fechaNacimiento: '2008-01-25',
        telefonoFijo: '',
        celular: '3008765432',
        gmail: 'anammoreno25@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Calle 10 #30-45',
        cursos: [
            { codigo: '2022105', año: '2022', grado: '10', grupo: 'A', estado: 'En curso', promedio: '' },
            { codigo: '2021105', año: '2021', grado: '9', grupo: 'A', estado: 'Aprobado', promedio: '4.7' }
        ]
    },
    {
        codigo: '2022106',
        tipoId: 'TI',
        numeroId: '1089789012',
        nombre: 'David Felipe Jiménez Castro',
        grado: '11',
        grupo: 'A',
        estado: 'En curso',
        primerNombre: 'David',
        segundoNombre: 'Felipe',
        primerApellido: 'Jiménez',
        segundoApellido: 'Castro',
        genero: 'M',
        fechaNacimiento: '2007-09-14',
        telefonoFijo: '6047890123',
        celular: '3126543210',
        gmail: 'davidfjimenez14@gmail.com',
        ciudad: 'Bogotá',
        direccion: 'Carrera 15 #85-23',
        cursos: [
            { codigo: '2022106', año: '2022', grado: '11', grupo: 'A', estado: 'En curso', promedio: '' },
            { codigo: '2021106', año: '2021', grado: '10', grupo: 'B', estado: 'Aprobado', promedio: '3.9' }
        ]
    },
    {
        codigo: '2022107',
        tipoId: 'TI',
        numeroId: '1088890123',
        nombre: 'Valentina Sofía Díaz Ruiz',
        grado: '11',
        grupo: 'A',
        estado: 'Aprobado',
        primerNombre: 'Valentina',
        segundoNombre: 'Sofía',
        primerApellido: 'Díaz',
        segundoApellido: 'Ruiz',
        genero: 'F',
        fechaNacimiento: '2007-04-03',
        telefonoFijo: '6048901234',
        celular: '3145678901',
        gmail: 'valentinasdiaz03@gmail.com',
        ciudad: 'Cali',
        direccion: 'Avenida 6N #25-60',
        cursos: [
            { codigo: '2022107', año: '2022', grado: '11', grupo: 'A', estado: 'Aprobado', promedio: '4.8' },
            { codigo: '2021107', año: '2021', grado: '10', grupo: 'A', estado: 'Aprobado', promedio: '4.6' }
        ]
    },
    {
        codigo: '2022108',
        tipoId: 'TI',
        numeroId: '1090901234',
        nombre: 'Santiago Alejandro Vargas Sánchez',
        grado: '11',
        grupo: 'B',
        estado: 'En curso',
        primerNombre: 'Santiago',
        segundoNombre: 'Alejandro',
        primerApellido: 'Vargas',
        segundoApellido: 'Sánchez',
        genero: 'M',
        fechaNacimiento: '2007-12-11',
        telefonoFijo: '',
        celular: '3187654321',
        gmail: 'santiagoavargas11@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Carrera 80 #32-18 Casa 5',
        cursos: [
            { codigo: '2022108', año: '2022', grado: '11', grupo: 'B', estado: 'En curso', promedio: '' }
        ]
    },
    {
        codigo: '2022109',
        tipoId: 'CC',
        numeroId: '1089012345',
        nombre: 'Isabella Mariana Gutiérrez Montoya',
        grado: '11',
        grupo: 'B',
        estado: 'En curso',
        primerNombre: 'Isabella',
        segundoNombre: 'Mariana',
        primerApellido: 'Gutiérrez',
        segundoApellido: 'Montoya',
        genero: 'F',
        fechaNacimiento: '2007-06-28',
        telefonoFijo: '6049012345',
        celular: '3203456789',
        gmail: 'isabellamgutierrez28@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Calle 33 #70-45 Apto 202',
        cursos: [
            { codigo: '2022109', año: '2022', grado: '11', grupo: 'B', estado: 'En curso', promedio: '' },
            { codigo: '2021108', año: '2021', grado: '10', grupo: 'C', estado: 'Aprobado', promedio: '4.1' }
        ]
    },
    {
        codigo: '2022110',
        tipoId: 'TI',
        numeroId: '1088123456',
        nombre: 'Miguel Ángel Rojas Mejía',
        grado: '9',
        grupo: 'A',
        estado: 'En curso',
        primerNombre: 'Miguel',
        segundoNombre: 'Ángel',
        primerApellido: 'Rojas',
        segundoApellido: 'Mejía',
        genero: 'M',
        fechaNacimiento: '2009-02-17',
        telefonoFijo: '6040123456',
        celular: '3112345678',
        gmail: 'miguelarojas17@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Carrera 52 #44-67',
        cursos: [
            { codigo: '2022110', año: '2022', grado: '9', grupo: 'A', estado: 'En curso', promedio: '' },
            { codigo: '2021109', año: '2021', grado: '8', grupo: 'B', estado: 'Aprobado', promedio: '3.5' }
        ]
    },
    {
        codigo: '2022111',
        tipoId: 'TI',
        numeroId: '1089234567',
        nombre: 'Salomé Catalina Ríos Quintero',
        grado: '9',
        grupo: 'A',
        estado: 'Aprobado',
        primerNombre: 'Salomé',
        segundoNombre: 'Catalina',
        primerApellido: 'Ríos',
        segundoApellido: 'Quintero',
        genero: 'F',
        fechaNacimiento: '2009-08-05',
        telefonoFijo: '',
        celular: '3134567890',
        gmail: 'salomecrios05@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Avenida El Poblado #14-23',
        cursos: [
            { codigo: '2022111', año: '2022', grado: '9', grupo: 'A', estado: 'Aprobado', promedio: '4.4' },
            { codigo: '2021110', año: '2021', grado: '8', grupo: 'A', estado: 'Aprobado', promedio: '4.0' }
        ]
    },
    {
        codigo: '2022112',
        tipoId: 'TI',
        numeroId: '1090345678',
        nombre: 'Nicolás Esteban Parra Vélez',
        grado: '9',
        grupo: 'B',
        estado: 'En curso',
        primerNombre: 'Nicolás',
        segundoNombre: 'Esteban',
        primerApellido: 'Parra',
        segundoApellido: 'Vélez',
        genero: 'M',
        fechaNacimiento: '2009-10-30',
        telefonoFijo: '6041234567',
        celular: '3156789012',
        gmail: 'nicolaseparra30@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Calle 65 #48-90',
        cursos: [
            { codigo: '2022112', año: '2022', grado: '9', grupo: 'B', estado: 'En curso', promedio: '' }
        ]
    },
    {
        codigo: '2022113',
        tipoId: 'TI',
        numeroId: '1088456789',
        nombre: 'Gabriela Andrea Álvarez Ospina',
        grado: '9',
        grupo: 'B',
        estado: 'Reprobado',
        primerNombre: 'Gabriela',
        segundoNombre: 'Andrea',
        primerApellido: 'Álvarez',
        segundoApellido: 'Ospina',
        genero: 'F',
        fechaNacimiento: '2009-03-21',
        telefonoFijo: '6042345678',
        celular: '3178901234',
        gmail: 'gabrielaaalvarez21@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Carrera 43A #12-56',
        cursos: [
            { codigo: '2022113', año: '2022', grado: '9', grupo: 'B', estado: 'Reprobado', promedio: '2.1' },
            { codigo: '2021111', año: '2021', grado: '8', grupo: 'C', estado: 'Aprobado', promedio: '3.0' }
        ]
    },
    {
        codigo: '2022114',
        tipoId: 'TI',
        numeroId: '1089567890',
        nombre: 'Mateo José Cardona Restrepo',
        grado: '9',
        grupo: 'C',
        estado: 'En curso',
        primerNombre: 'Mateo',
        segundoNombre: 'José',
        primerApellido: 'Cardona',
        segundoApellido: 'Restrepo',
        genero: 'M',
        fechaNacimiento: '2009-05-09',
        telefonoFijo: '',
        celular: '3190123456',
        gmail: 'mateojcardona09@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Avenida Las Vegas #23-45',
        cursos: [
            { codigo: '2022114', año: '2022', grado: '9', grupo: 'C', estado: 'En curso', promedio: '' },
            { codigo: '2021112', año: '2021', grado: '8', grupo: 'A', estado: 'Aprobado', promedio: '3.7' }
        ]
    },
    {
        codigo: '2022115',
        tipoId: 'TI',
        numeroId: '1090678901',
        nombre: 'Sofía Alejandra Muñoz Arango',
        grado: '9',
        grupo: 'C',
        estado: 'En curso',
        primerNombre: 'Sofía',
        segundoNombre: 'Alejandra',
        primerApellido: 'Muñoz',
        segundoApellido: 'Arango',
        genero: 'F',
        fechaNacimiento: '2009-11-16',
        telefonoFijo: '6043456789',
        celular: '3121234567',
        gmail: 'sofiaamunoz16@gmail.com',
        ciudad: 'Medellín',
        direccion: 'Carrera 65B #78-90 Apto 401',
        cursos: [
            { codigo: '2022115', año: '2022', grado: '9', grupo: 'C', estado: 'En curso', promedio: '' }
        ]
    }
]